In [123]:
# In this example, we will clean up a dataset, and try to find out which movie genre was the most popular in different years
# Let's go ahead

In [124]:
import pandas as pd

df = pd.read_csv(r"C:\Users\User\Downloads\movies.csv")

In [125]:
df.shape

(9999, 9)

In [126]:
# Let's set max rows display amount to 100, so we will be able to scroll

pd.set_option('display.max_rows', 20)

In [127]:
df.head(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
5,Outer Banks,(2020– ),"\nAction, Crime, Drama",7.6,\nA group of teenagers from the wrong side of ...,"\n \n Stars:\nChase Stokes, \nMa...","25,858",50.0,NaN
6,The Last Letter from Your Lover,(2021),"\nDrama, Romance",6.8,\nA pair of interwoven stories set in the past...,\n Director:\nAugustine Frizzell\n| \n S...,"5,283",110.0,NaN
7,Dexter,(2006–2013),"\nCrime, Drama, Mystery",8.6,"\nBy day, mild-mannered Dexter is a blood-spat...","\n \n Stars:\nMichael C. Hall, \...","665,387",53.0,NaN
8,Never Have I Ever,(2020– ),\nComedy,7.9,\nThe complicated life of a modern-day first g...,\n \n Stars:\nMaitreyi Ramakrish...,"34,530",30.0,NaN
9,Virgin River,(2019– ),"\nDrama, Romance",7.4,"\nSeeking a fresh start, nurse practitioner Me...",\n \n Stars:\nAlexandra Breckenr...,"27,279",44.0,NaN

In [128]:
# as we can see the same situation with unclean data is everywhere in this dataset.
# let's begin to clean it up
# First of all, I would like to remove parantheses form YEAR column

# And I think it would be better, to split YEAR column into two columns, Starting_Year and Ending_Year. 

df['YEAR'] = df['YEAR'].str.strip('()')
df['Starting_Year'] = df['YEAR'].str[:4]
df['Ending_Year'] = df['YEAR'].str[-5:]

# We get the dashes in the end of some values in Ending_Year, so I decided to replace with empty string everything except numbers
df['Ending_Year'] = df['Ending_Year'].str.replace(r'\D','', regex=True)

# Now it looks good. Lets drop YEAR column and change the indexes of two new columns to bring them forward
df.drop('YEAR', axis=1, inplace=True)

In [129]:
df.head(10)

,MOVIES,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,Starting_Year,Ending_Year
0,Blood Red Sky,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN,2021,2021
1,Masters of the Universe: Revelation,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN,2021,021
2,The Walking Dead,"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN,2010,2022
3,Rick and Morty,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN,2013,013
4,Army of Thieves,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN,2021,2021
5,Outer Banks,"\nAction, Crime, Drama",7.6,\nA group of teenagers from the wrong side of ...,"\n \n Stars:\nChase Stokes, \nMa...","25,858",50.0,NaN,2020,020
6,The Last Letter from Your Lover,"\nDrama, Romance",6.8,\nA pair of interwoven stories set in the past...,\n Director:\nAugustine Frizzell\n| \n S...,"5,283",110.0,NaN,2021,2021
7,Dexter,"\nCrime, Drama, Mystery",8.6,"\nBy day, mild-mannered Dexter is a blood-spat...","\n \n Stars:\nMichael C. Hall, \...","665,387",53.0,NaN,2006,2013
8,Never Have I Ever,\nComedy,7.9,\nThe complicated life of a modern-day first g...,\n \n Stars:\nMaitreyi Ramakrish...,"34,530",30.0,NaN,2020,020
9,Virgin River,"\nDrama, Romance",7.4,"\nSeeking a fresh start, nurse practitioner Me...",\n \n Stars:\nAlexandra Breckenr...,"27,279",44.0,NaN,2019,019

In [130]:
df.columns

Index(['MOVIES', 'GENRE', 'RATING', 'ONE-LINE', 'STARS', 'VOTES', 'RunTime',
       'Gross', 'Starting_Year', 'Ending_Year'],
      dtype='object')

In [131]:
# Let's drop columns we are not gonna use
columns = ['ONE-LINE', 'RunTime', 'Gross', 'STARS']
df.drop(columns, axis =1)

,MOVIES,GENRE,RATING,VOTES,Starting_Year,Ending_Year
0,Blood Red Sky,"\nAction, Horror, Thriller",6.1,"21,062",2021,2021
1,Masters of the Universe: Revelation,"\nAnimation, Action, Adventure",5.0,"17,870",2021,021
2,The Walking Dead,"\nDrama, Horror, Thriller",8.2,"885,805",2010,2022
3,Rick and Morty,"\nAnimation, Adventure, Comedy",9.2,"414,849",2013,013
4,Army of Thieves,"\nAction, Crime, Horror",NaN,NaN,2021,2021
...,...,...,...,...,...,...
9994,The Imperfects,"\nAdventure, Drama, Fantasy",NaN,NaN,2021,021
9995,Arcane,"\nAnimation, Action, Adventure",NaN,NaN,2021,021
9996,Heart of Invictus,"\nDocumentary, Sport",NaN,NaN,2022,022
9997,The Imperfects,"\nAdventure, Drama, Fantasy",NaN,NaN,2021,021
9998,The Imperfects,"\nAdventure, Drama, Fantasy",NaN,NaN,2021,021

In [132]:
df.columns

Index(['MOVIES', 'GENRE', 'RATING', 'ONE-LINE', 'STARS', 'VOTES', 'RunTime',
       'Gross', 'Starting_Year', 'Ending_Year'],
      dtype='object')

In [133]:
# I want to change the order of columns

new_order = ['MOVIES', 'Starting_Year', 'Ending_Year', 'GENRE', 'RATING', 'VOTES']
df = df[new_order]
df.head(5)

,MOVIES,Starting_Year,Ending_Year,GENRE,RATING,VOTES
0,Blood Red Sky,2021,2021,"\nAction, Horror, Thriller",6.1,"21,062"
1,Masters of the Universe: Revelation,2021,021,"\nAnimation, Action, Adventure",5.0,"17,870"
2,The Walking Dead,2010,2022,"\nDrama, Horror, Thriller",8.2,"885,805"
3,Rick and Morty,2013,013,"\nAnimation, Adventure, Comedy",9.2,"414,849"
4,Army of Thieves,2021,2021,"\nAction, Crime, Horror",NaN,NaN

In [134]:
# Now it looks better 
# Let's go ahead and remove new line characters from GENRE column

df['GENRE'] = df['GENRE'].str.replace('\n', '')
df.head(10)

,MOVIES,Starting_Year,Ending_Year,GENRE,RATING,VOTES
0,Blood Red Sky,2021,2021,"Action, Horror, Thriller",6.1,"21,062"
1,Masters of the Universe: Revelation,2021,021,"Animation, Action, Adventure",5.0,"17,870"
2,The Walking Dead,2010,2022,"Drama, Horror, Thriller",8.2,"885,805"
3,Rick and Morty,2013,013,"Animation, Adventure, Comedy",9.2,"414,849"
4,Army of Thieves,2021,2021,"Action, Crime, Horror",NaN,NaN
5,Outer Banks,2020,020,"Action, Crime, Drama",7.6,"25,858"
6,The Last Letter from Your Lover,2021,2021,"Drama, Romance",6.8,"5,283"
7,Dexter,2006,2013,"Crime, Drama, Mystery",8.6,"665,387"
8,Never Have I Ever,2020,020,Comedy,7.9,"34,530"
9,Virgin River,2019,019,"Drama, Romance",7.4,"27,279"

In [135]:
# Now it is almost ready for our calculations. 
# We just need to set all NaN values equal to 0

df.fillna(0, inplace=True)

In [136]:
df.head(10)

,MOVIES,Starting_Year,Ending_Year,GENRE,RATING,VOTES
0,Blood Red Sky,2021,2021,"Action, Horror, Thriller",6.1,"21,062"
1,Masters of the Universe: Revelation,2021,021,"Animation, Action, Adventure",5.0,"17,870"
2,The Walking Dead,2010,2022,"Drama, Horror, Thriller",8.2,"885,805"
3,Rick and Morty,2013,013,"Animation, Adventure, Comedy",9.2,"414,849"
4,Army of Thieves,2021,2021,"Action, Crime, Horror",0.0,0
5,Outer Banks,2020,020,"Action, Crime, Drama",7.6,"25,858"
6,The Last Letter from Your Lover,2021,2021,"Drama, Romance",6.8,"5,283"
7,Dexter,2006,2013,"Crime, Drama, Mystery",8.6,"665,387"
8,Never Have I Ever,2020,020,Comedy,7.9,"34,530"
9,Virgin River,2019,019,"Drama, Romance",7.4,"27,279"